# Generated by Django 4.1.7 on 2023-03-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=250)),
                ('speed', models.IntegerField(default=50)),
            ],
        ),
    ]
